package com.pierangeloc.akka.persistence

import akka.actor._
import akka.persistence._

case class Cmd(data: String)
case class Evt(data: String)

//state of the actor
case class ExampleState(events: List[String] = Nil) {
  def updated(evt: Evt): ExampleState = copy(evt.data :: events)
  def size: Int = events.length
  override def toString: String = events.reverse.toString
}

class ExamplePersistentActor extends PersistentActor {
  override def persistenceId = "sample-id-1"

  var state = ExampleState()

  //update internal state once the event has been persisted
  def updateState(event: Evt): Unit =
    state = state.updated(event)

  def numEvents =
    state.size

  //how state should be recovered by handling events and SnapshotOffers (predefined in akka persistence)
  val receiveRecover: Receive = {
    case evt: Evt                                 => updateState(evt)
    case SnapshotOffer(_, snapshot: ExampleState) => state = snapshot
  }

  //command handler. Calls the persist method with Event(s) generated by this command
  val receiveCommand: Receive = {
    case Cmd(data) =>
      persist(Evt(s"${data}-${numEvents}"))(updateState)
      persist(Evt(s"${data}-${numEvents + 1}")) { event =>
        updateState(event)
        context.system.eventStream.publish(event)
      }
    case "snap"  => saveSnapshot(state)
    case "print" => println(state)
  }

}
